var cat_selection="Jeux_Video",data_nest=d3.nest().key(function(a){return a.category}).map(data_total.sort(function(a,b){return a.revenue1-b.revenue1})),data_total_sort=data_total.sort(function(a,b){return a.category>b.category}),data_nest_category=d3.nest().key(function(a){return a.name}).map(data_category.sort(function(a,b){return b.name>a.name})),data=data_nest[cat_selection],data1=data_nest_category[cat_selection][0].link.sort(function(a,b){return b.value-a.value}),w0=document.body.clientWidth/
2,h0=document.body.clientHeight*0.98,wb=500,hb=wb/2,wa=w0*0.9,ha=h0/3,wi=w0*0.7,hi=h0/2,offset_i=w0/7.7,translate_i=offset_i*1.7,translate_a=translate_i*0,translate_barres=translate_i,max_lettres=w0/18,w=w0*0.65,h=h0*0.55,r0=h*0.45,r1=r0*1.2,num_produits=data.length,minV=d3.min(data_total,function(a){return a.revenue1}),maxV=d3.max(data_total,function(a){return a.revenue1}),max_cat=[];
data_category.forEach(function(a){max_cat.push({max:d3.max(a.link,function(a){return a.value}),min:d3.min(a.link,function(a){return a.value})})});var minV1=d3.min(max_cat,function(a){return a.min}),maxV1=d3.max(max_cat,function(a){return a.max}),echelles=[],top_correlation=[],arbre={};
data_total.forEach(function(a){echelles.push({max_indice:d3.max(a.connections,function(a){return a.indice}),min_indice:d3.min(a.connections,function(a){return a.indice}),max_revenue:d3.max(a.connections,function(a){return a.revenue}),min_revenue:d3.min(a.connections,function(a){return a.revenue}),max_quantity:d3.max(a.connections,function(a){return a.quantity}),min_quantity:d3.min(a.connections,function(a){return a.quantity})})});
var max_indice=d3.max(echelles,function(a){return a.max_indice}),min_indice=d3.min(echelles,function(a){return a.min_indice}),max_revenue=d3.max(echelles,function(a){return a.max_revenue}),min_revenue=d3.min(echelles,function(a){return a.min_revenue}),max_quantity=d3.max(echelles,function(a){return a.max_quantity}),min_quantity=d3.min(echelles,function(a){return a.min_quantity}),height=d3.scale.linear().domain([minV,maxV]).range([0,100]),height1=d3.scale.linear().domain([minV1,maxV1]).range([0,100]),
offset=d3.scale.linear().domain([minV,maxV]).range([-1.2,-1.2]),offset1=d3.scale.linear().domain([minV1,maxV1]).range([1.1,1.1]),angle1=d3.scale.ordinal().domain(d3.range(0,data1.length)).rangeBands([0.02*Math.PI,0.98*Math.PI]),max_bars=d3.max(bars,function(a){return a.value}),min_bars=d3.min(bars,function(a){return a.value}),width_bars=d3.scale.linear().domain([min_bars,max_bars]).range([20,200]),color_line=d3.scale.linear().domain([min_indice,max_indice]).range(["lightgrey","grey"]),color_indice=
d3.scale.linear().domain([min_indice,max_indice]).range(["lightgrey","grey"]),color_revenue=d3.scale.linear().domain([min_revenue,max_revenue]).range(["lightgrey","grey"]),color_quantity=d3.scale.linear().domain([min_quantity,max_quantity]).range(["#60b59e","#086340"]),color_category=d3.scale.category20(),darker_indice=d3.scale.linear().domain([min_indice,max_indice]).range([0.5,1]),size=d3.scale.linear().domain([min_indice,max_indice]).range([1.5,4]),width_indice=d3.scale.linear().domain([min_indice,
max_indice]).range([20,w0/18]),width_revenue=d3.scale.linear().domain([min_revenue,max_revenue]).range([20,w0/18]),width_quantity=d3.scale.linear().domain([min_quantity,max_quantity]).range([20,w0/18]),cluster=d3.layout.cluster().size([h0/3,50]),cluster_top=d3.layout.cluster().size([h0*0.8,200]),diagonal=d3.svg.diagonal().projection(function(a){return[a.y,a.x]}),diagonal_top=d3.svg.diagonal().projection(function(a){return[a.y,a.x+13]});
line=d3.svg.chord().startAngle(function(a){return(a.startAngle+a.endAngle)/2}).endAngle(function(a){return(a.startAngle+a.endAngle)/2}).radius(h/2-15);angles={};data_length=[];connections=[];data_bars=[];function fangle(a){return d3.scale.ordinal().domain(d3.range(0,a)).rangeBands([1.02*Math.PI,1.98*Math.PI])}function couper(a,b){return a.slice(0,b)}var format=d3.format("1f"),mille=d3.format(",");
data_category.forEach(function(a){l=data_nest[a.name].length;data_nest[a.name].forEach(function(a,c){var d=fangle(l)(c);angles[a.name]={startAngle:d,endAngle:d+fangle(l).rangeBand()/2}});data_length.push({name:a.name,longueur:l})});data_length.sort(function(a,b){return b.name>a.name}).forEach(function(a){if(a.longueur>10)return data_bars.push({name:a.name,value:d3.nest().key(function(a){return a.name}).map(bars)[a.name][0].value})});
data1.forEach(function(a,b){var c=angle1(b);angles[a.name]={startAngle:c,endAngle:c+angle1.rangeBand()/2}});data_category.forEach(function(a){data_nest[a.name].forEach(function(a){a.connections.forEach(function(c){connections.push({source:angles[a.name],target:angles[c.category],indice:c.indice,index:a.name,category:a.category,category_target:c.category,revenue:c.revenue,revenue_cross:c.revenue_cross,name_target:c.name})})})});
var top50=connections.sort(function(a,b){return b.indice-a.indice}).slice(0,25);data_total.forEach(function(a){arbre[a.name]={name:a.name,children:a.connections}});top50.forEach(function(a){top_correlation.push({name:a.index,level:"b",children:[{name:a.name_target,category:a.category_target,indice:a.indice,revenue:a.revenue_cross,quantity:a.quantity}]})});
var data_top_correlation=[{name:"",level:"a",children:top_correlation}],start_date=couper(data_date[0].dateStart,10),end_date=couper(data_date[1].dateEnd,10);d3.select("#sous_titre").append("text").text("From "+start_date+" to "+end_date);var vis=d3.select("#chord").append("svg:svg").attr("width",w0).attr("height",h0*0.9).attr("id","container").append("svg:g").attr("transform","translate("+w0/2+","+h0/2.3+")");
vis.append("svg:text").attr("class","text").attr("id","text_intro").attr("dx",-w0/6).attr("dy",-h0/6).text("Choose a category to start.");
var produits=d3.select("#container").append("svg:svg").attr("width",w0).attr("height",h0).append("svg:g").attr("transform","translate("+w0/2+","+h0/2.3+")"),cat=d3.select("#container").append("svg:svg").attr("width",w0).attr("height",h0).append("svg:g").attr("transform","translate("+w0/2+","+h0/2.3+")"),base_arbre=d3.select("#arbre").append("svg:svg").attr("width",wa).attr("height",ha).attr("z-index",1).attr("id","base_arbre"),connections_nest=d3.nest().key(function(a){return a.category}).map(connections);
function groupTicks(a){return d3.range(1).map(function(){return{angle:190*angles[a.name].startAngle,label:a.name,value:a.revenue1}})}function groupTicks1(a){return d3.range(1).map(function(){return{angle:190*angles[a.name].startAngle,label:a.name,value:a.value}})}
function fade(a,b){d3.selectAll("path.chord").filter(function(a){return a.index!=b}).transition().attr("visibility",function(){if(a==0)return"hidden";if(a==1)return"visible"});if(a==0)return render_arbre(b);a==1&&(d3.select("#vis_tree").remove(),d3.select("#titre_arbre").selectAll("text").remove(),d3.select("#sous_titre_arbre").selectAll("text").remove())}
function fade_cat(a,b){d3.selectAll("path.chord").filter(function(a){return a.index!=b}).transition().attr("visibility",function(){if(a==0)return"hidden";if(a==1)return"visible"})}
function render_chord(a){var b=data_nest[a],c=connections_nest[a],d=d3.nest().key(function(a){return a.name}).map(data_length)[a][0].longueur,e=data_nest_category[a][0].link;d3.select("#titre2").selectAll("text").remove();d3.select("#sous_titre2").selectAll("text").remove();d3.select("#titre2").append("text").text(a+" | Correlation of top "+d+" products");d3.select("#sous_titre2").append("text").text("Mouse over on products to get full correlation details");produits.selectAll("path").data(b).enter().append("svg:path").attr("d",
d3.svg.arc().innerRadius(h/2-15).outerRadius(function(a){return h/2-10+height(a.revenue1)}).startAngle(function(a){return angles[a.name].startAngle}).endAngle(function(a){return angles[a.name].endAngle})).attr("a",function(a){return a.name}).attr("fill",function(a){return color_category(a.category)}).attr("opacity",0.7).on("mouseover",function(a){return fade(0,a.name)}).on("mouseout",function(a){return fade(1,a.name)});produits.append("svg:g").selectAll("g").data(b).enter().append("svg:g").selectAll("g").data(groupTicks).enter().append("svg:g").attr("transform",
function(a){return"rotate("+(a.angle/Math.PI*0.95+91)+")translate("+r0*offset(a.value)+",0)"}).append("svg:text").attr("x",8).attr("dy",".35em").attr("class","tticks").attr("opacity",1).attr("text-anchor","end").text(function(a){return couper(a.label,25)}).on("mouseover",function(a){return fade(0,a.label)}).on("mouseout",function(a){return fade(1,a.label)});vis.selectAll("path.c").data(c).enter().append("svg:path").attr("d",line).attr("class","chord").attr("stroke",function(a){return color_category(a.category_target)}).attr("opacity",
function(a){return darker_indice(a.indice)}).attr("stroke-width",function(a){return size(a.indice)});cat.selectAll("path").data(e).enter().append("svg:path").attr("d",d3.svg.arc().innerRadius(h/2-15).outerRadius(function(a){return h/2-10+height1(a.value)}).startAngle(function(a){return angles[a.name].startAngle}).endAngle(function(a){return angles[a.name].endAngle})).attr("opacity",0.7).attr("fill",function(a){return color_category(a.name)});cat.append("svg:g").selectAll("g").data(e).enter().append("svg:g").selectAll("g").data(groupTicks1).enter().append("svg:g").attr("transform",
function(a){return"rotate("+(a.angle/Math.PI*0.95-88)+")translate("+r0*offset1(a.value)+",0)"}).append("svg:text").attr("x",8).attr("dy",".35em").attr("class","tticks").text(function(a){return a.label})}
function render_arbre(a){d3.select("#titre_arbre").selectAll("text").remove();d3.select("#sous_titre_arbre").selectAll("text").remove();d3.select("#titre_arbre").append("text").text("Product correlation details");d3.select("#sous_titre_arbre").append("text").text(a);var b=d3.select("#base_arbre").append("svg:svg").attr("width",wa).attr("height",ha).attr("id","vis_tree"),c=b.append("svg:svg").attr("width",wa).attr("id","arbre_vis").append("svg:g").attr("transform","translate("+translate_i*1.3+", 10)"),
a=cluster.nodes(arbre[a]);c.selectAll("path.link").data(cluster.links(a)).enter().append("svg:path").attr("class","link").attr("d",diagonal).attr("stroke",function(a){return color_category(a.target.category)}).attr("stroke-width",function(a){return size(a.target.indice)}).attr("opacity",function(a){return darker_indice(a.target.indice)});c.selectAll("g.node").data(a).enter().append("svg:g").attr("class","node").attr("transform",function(a){return"translate("+a.y+","+a.x+")"}).append("svg:text").attr("dx",
function(a){return a.children?-translate_i*1.3:10}).attr("dy",3).text(function(a){return couper(a.name,max_lettres)});b=b.append("svg:svg").attr("id","indice").append("svg:g").attr("transform","translate("+translate_a+", 10)");b.selectAll("rect").data(a).enter().append("svg:rect").attr("width",function(a){return width_indice(a.indice)}).attr("x",wi).attr("height",5).attr("y",function(a){return a.x-5}).attr("fill",function(a){return color_indice(a.indice)});b.selectAll("text").data(a).enter().append("svg:text").attr("x",
function(a){return width_indice(a.indice)}).attr("dx",wi+5).attr("dy",function(a){return a.x+1.5}).attr("class","node").text(function(a){return format(a.indice)=="NaN"?"":mille(format(a.indice))});b.append("svg:text").attr("y",0).attr("class","node_titre").attr("dx",wi).text("Cross Index")}window.addEventListener("keypress",render_top_correlation,false);
function render_top_correlation(){d3.select("#text_intro").remove();produits.selectAll("path").remove();produits.selectAll("g").remove();vis.selectAll("path").remove();cat.selectAll("path").remove();cat.selectAll("g").remove();d3.select("#top_correlation_container").remove();d3.select("#titre2").selectAll("text").remove();d3.select("#sous_titre2").selectAll("text").remove();d3.select("#titre2").selectAll("text").remove();d3.select("#sous_titre2").selectAll("text").remove();d3.select("#titre2").append("text").text("All Categories | Top correlated products");
d3.select("#sous_titre2").append("text").text("Display top 25 correlated products over the period");var a=d3.select("#container").append("svg:g").attr("id","top_correlation_container").attr("transform","translate("+w0/6.3+", 10)"),b=cluster_top.nodes(data_top_correlation[0]);a.selectAll("path.link").data(cluster_top.links(b)).enter().append("svg:path").attr("class","link").attr("level",function(a){return a.source.level}).attr("stroke",function(a){return color_category(a.target.category)}).attr("stroke-width",
function(a){return size(a.target.indice)}).attr("d",diagonal_top);a.selectAll("g.node").data(b).enter().append("svg:g").attr("class","node").attr("transform",function(a){return"translate("+a.y+","+a.x+")"}).append("svg:text").attr("dx",function(a){return a.children?-8:8}).attr("dy",16).attr("text-anchor",function(a){return a.children?"end":"start"}).text(function(a){return couper(a.name,w0/18)});d3.selectAll("[level=a]").remove();a=a.append("svg:svg").attr("id","indice_top").append("svg:g").attr("transform",
"translate(0, 0)");a.selectAll("rect").data(b).enter().append("svg:rect").attr("width",function(a){return width_indice(a.indice)}).attr("x",w0/1.5).attr("height",5).attr("y",function(a){return a.x+10}).attr("opacity",0.8).attr("fill",function(a){return color_indice(a.indice)});a.selectAll("text").data(b).enter().append("svg:text").attr("x",function(a){return width_indice(a.indice)}).attr("dx",w0/1.5+5).attr("y",function(a){return a.x+16}).attr("class","node").text(function(a){return format(a.indice)==
"NaN"?"":format(a.indice)});a.append("svg:text").attr("y",10).attr("class","node_titre").attr("dx",w0/1.5).text("Cross Index")}function fade_barre(a,b){barres.select("#"+b).attr("opacity",a)}var barres=d3.select("#barres").append("svg:svg").attr("width",wb).attr("height",hb);
barres.selectAll("rect").data(data_bars.sort(function(a,b){return b.value-a.value})).enter().append("svg:rect").attr("y",function(a,b){return 10+b*21}).attr("x",translate_barres).attr("width",function(a){return width_bars(a.value)}).attr("height",19).attr("cursor","pointer").attr("id",function(a){return a.name}).attr("opacity",0.6).on("mouseover",function(a){return fade_barre(1,a.name)}).on("mouseout",function(a){return fade_barre(0.6,a.name)}).attr("name",function(a){return a.name}).attr("fill",
function(a){return color_category(a.name)}).on("click",function(){d3.select("#text_intro").remove();var a=d3.select(this).attr("name");produits.selectAll("path").remove();produits.selectAll("g").remove();vis.selectAll("path").remove();cat.selectAll("path").remove();cat.selectAll("g").remove();d3.select("#top_correlation_container").remove();d3.select("#titre2").selectAll("text").remove();d3.select("#sous_titre2").selectAll("text").remove();render_chord(a)});
barres.selectAll("text").data(data_bars.sort(function(a,b){return b.value-a.value})).enter().append("svg:text").attr("y",function(a,b){return 10+b*21}).attr("x",0).attr("dy","1.2em").attr("class","barres").attr("text-anchor","top").text(function(a){return a.name});var numbers=barres.append("svg:svg").attr("width",wb).attr("height",hb);
numbers.selectAll("text").data(data_bars.sort(function(a,b){return b.value-a.value})).enter().append("svg:text").attr("y",function(a,b){return 10+b*21}).attr("x",function(a){return translate_barres*1.05+width_bars(a.value)}).attr("dy","1.2em").attr("class","barres").text(function(a){return mille(format(a.value))+" euros"});